from django.contrib import admin
from .models import TaxConfig, PayrollRun, Payslip


@admin.register(TaxConfig)
class TaxConfigAdmin(admin.ModelAdmin):
    """
    Admin interface for managing Australian tax brackets.
    Displays all bracket fields in list view, ordered by min income
    so brackets are always shown in ascending order.
    """

    # Columns shown in the admin list view
    list_display = [
        'financial_year',
        'min_income',
        'max_income',
        'tax_rate',
    ]

    # Default sort — lowest bracket first for easy reading
    ordering = ['min_income']

    # Allow filtering by financial year in the right sidebar
    list_filter = ['financial_year']

    # Allow searching by financial year in the search bar
    search_fields = ['financial_year']


@admin.register(PayrollRun)
class PayrollRunAdmin(admin.ModelAdmin):
    """
    Admin interface for viewing completed payroll runs.
    Read-only in practice — runs should only be created via the
    payroll module UI to ensure atomic payslip generation.
    """

    # Show key fields for each run at a glance
    list_display = [
        'pay_start',
        'pay_end',
        'pay_date',
        'total_amount',
        'processed_by',
        'created_at',
    ]

    # Most recent runs at the top
    ordering = ['-created_at']

    # Allow filtering by pay date in the right sidebar
    list_filter = ['pay_date']

    # Allow searching by the username of who processed the run
    search_fields = ['processed_by__username']


@admin.register(Payslip)
class PayslipAdmin(admin.ModelAdmin):
    """
    Admin interface for viewing individual employee payslips.
    Payslips are auto-generated by run_payroll() and should not
    be manually created or edited via admin.
    """

    # Show key payslip fields for quick review
    list_display = [
        'employee',
        'payroll_run',
        'gross_pay',
        'tax_amount',
        'deductions',
        'generated_at',
    ]

    # Most recently generated payslips at the top
    ordering = ['-generated_at']

    # Allow filtering by payroll run date
    list_filter = ['payroll_run__pay_date']

    # Allow searching by employee name
    search_fields = [
        'employee__first_name',
        'employee__last_name',
        'employee__email',
    ]
